### ISSUE TITLE
Can't save derivation containing custom rewrite

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#103]
I tried to save a derivation where the custom rewrite involves a non-zero phase Fraction(1,4) (the same rewrite as in #102 ). I then got the following exception:
```
Traceback (most recent call last):
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\mainwindow.py", line 292, in save_file
    data = self.active_panel.proof_model.to_json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\proof.py", line 124, in to_json
    proof_steps.append(step.to_json())
                       ^^^^^^^^^^^^^^
  File "C:\Users\jweteri\Documents\Projects\zxlive\zxlive\proof.py", line 21, in to_json
    "diff": self.diff.to_json()
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\Documents\Projects\zxlive\../pyzx\pyzx\graph\diff.py", line 124, in to_json
    return json.dumps({
           ^^^^^^^^^^^^
  File "C:\Users\jweteri\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\jweteri\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Fraction is not JSON serializable
```

**Comment by RazinShaikh** [comment]
This error is not related to custom rewrites. I am able to reproduce this in any derivation containing a Fraction phase. This is a bug in PyZX's `to_json` method of `GraphDiff`. It does not do anything special when converting `Fraction` to json. This seems like something that should already exist somewhere in PyZX. Do you know how phases are usually converted to json in pyzx?
