### ISSUE TITLE
Symbolic angles: spider fusion is broken

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#59]
When fusing spiders with symbolic angles the following exception is raised:

```
Traceback (most recent call last):
  File "C:\Users\jvdwe\Documents\Projects\zxlive\zxlive\proof_panel.py", line 122, in _vertex_dropped_onto
    pyzx.basicrules.fuse(g, w, v)
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\basicrules.py", line 202, in fuse
    g.add_to_phase(v1, g.phase(v2))
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\graph\graph_s.py", line 257, in add_to_phase
    self._phase[vertex] = old_phase + phase
TypeError: unsupported operand type(s) for +: 'FunctionClass' and 'Symbol'
Traceback (most recent call last):
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\graph\graph_s.py", line 255, in add_to_phase
    self._phase[vertex] = (old_phase + Fraction(phase)) % 2
TypeError: unsupported operand type(s) for +: 'FunctionClass' and 'Fraction'
```

**Comment by y-richie-y** [comment]
it seems to work for me. how do i reproduce this?

**Comment by jvdwetering** [comment]
Create two connected spiders which both have a non-zero angle. For instance, 'alpha' and 'beta'

**Comment by y-richie-y** [comment]
Seems to specifically fail when we use `beta`.
